site_name: Sample Site
theme:
  name: 'material'
  custom_dir: docs
  extra_css:
    - stylesheets/extra.css
  features:
    - search
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.tab.link
    - content.code.copy
  language: en
 
markdown_extensions:
  - pymdownx.highlight
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins:
  - search:
  - blog:
      pagination: true
      pagination_per_page: 2
      pagination_url_format: "page/{page}"

palette:
  - primary: indigo

nav:
- Profile:
  - About Us: 'About_us.md'
  - Contact us: 'Contact_us.md'
  - Our Vision: 'Our_vision.md'

- SQL Joins:
  - SQL Joins: 'SQL Joins.md'
  - INNER JOIN: 'INNER_JOIN.md'
  - FULL JOIN: 'FULL_JOIN.md'
  - RIGHT JOIN: 'RIGHT_JOIN.md'
  - LEFT JOIN: 'LEFT_JOIN.md'
    


copyright: Copyright © 2023 Original Creations
